"use client";

import React from "react";
import { ProposalSummaryMetrics } from "@/lib/mockTradeProposalsData";
import { FileText, ShieldCheck, UserCheck, Bot, ArrowRight } from "lucide-react";

interface ProposalSummaryHeaderProps {
  metrics: ProposalSummaryMetrics;
  className?: string;
}

export function ProposalSummaryHeader({
  metrics,
  className = "",
}: ProposalSummaryHeaderProps) {
  return (
    <div className={`space-y-4 ${className}`}>
      {/* 1. Page Header & Institutional Responsibility Pipeline */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 p-4 rounded-lg bg-surface border border-border-color">
        <div className="flex items-center gap-3.5">
          <div className="p-2.5 rounded bg-bg-950 border border-cyan-500/40 text-cyan-400 shadow-[0_0_12px_rgba(0,229,255,0.2)]">
            <FileText size={22} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-bold font-mono tracking-tight text-gray-100">
                Trade Proposals
              </h1>
              <span className="px-1.5 py-0.2 rounded bg-cyan-dim/30 border border-cyan-500/30 text-[10px] font-mono text-cyan-300 font-bold">
                DECISION PIPELINE
              </span>
            </div>
            <p className="text-xs text-gray-400 font-sans">
              Structured trading decisions generated by Hermes and validated by the Deterministic Risk Engine.
            </p>
          </div>
        </div>

        {/* Responsibility Tri-Pillar Architecture Graphic */}
        <div className="flex flex-wrap items-center gap-2 p-2.5 rounded bg-bg-950 border border-border-color text-xs font-mono select-none">
          <div className="flex items-center gap-1.5">
            <Bot size={13} className="text-cyan-400" />
            <div className="flex flex-col">
              <span className="text-[10px] font-bold text-cyan-300">HERMES</span>
              <span className="text-[9px] text-gray-400">Proposes</span>
            </div>
          </div>

          <ArrowRight size={12} className="text-gray-600" />

          <div className="flex items-center gap-1.5">
            <ShieldCheck size={13} className="text-profit" />
            <div className="flex flex-col">
              <span className="text-[10px] font-bold text-profit">RISK ENGINE</span>
              <span className="text-[9px] text-gray-400">Validates</span>
            </div>
          </div>

          <ArrowRight size={12} className="text-gray-600" />

          <div className="flex items-center gap-1.5">
            <UserCheck size={13} className="text-warning" />
            <div className="flex flex-col">
              <span className="text-[10px] font-bold text-warning">OWNER</span>
              <span className="text-[9px] text-gray-400">Authorizes</span>
            </div>
          </div>
        </div>
      </div>

      {/* 2. Top Summary Metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
        <div className="p-3 rounded-lg bg-surface border border-warning/40 space-y-1 shadow-[0_0_12px_rgba(245,158,11,0.06)]">
          <span className="text-[10px] font-mono uppercase text-warning font-bold">
            Pending Approval
          </span>
          <div className="font-mono text-2xl font-bold text-warning">
            {metrics.pendingApprovalCount}
          </div>
          <span className="text-[10px] font-mono text-gray-400 block">
            Owner decision required
          </span>
        </div>

        <div className="p-3 rounded-lg bg-surface border border-profit/40 space-y-1">
          <span className="text-[10px] font-mono uppercase text-profit font-bold">
            Risk Approved
          </span>
          <div className="font-mono text-2xl font-bold text-profit">
            {metrics.riskApprovedCount}
          </div>
          <span className="text-[10px] font-mono text-gray-400 block">
            Cleared all 7 checks
          </span>
        </div>

        <div className="p-3 rounded-lg bg-surface border border-border-color space-y-1">
          <span className="text-[10px] font-mono uppercase text-gray-400">
            Under Review
          </span>
          <div className="font-mono text-2xl font-bold text-gray-200">
            {metrics.underReviewCount}
          </div>
          <span className="text-[10px] font-mono text-cyan-400 block">
            Awaiting VaR calculation
          </span>
        </div>

        <div className="p-3 rounded-lg bg-surface border border-border-color space-y-1">
          <span className="text-[10px] font-mono uppercase text-gray-400">
            Rejected
          </span>
          <div className="font-mono text-2xl font-bold text-loss">
            {metrics.rejectedCount}
          </div>
          <span className="text-[10px] font-mono text-gray-400 block">
            Risk constraints violated
          </span>
        </div>

        <div className="p-3 rounded-lg bg-surface border border-border-color space-y-1 col-span-2 sm:col-span-1">
          <span className="text-[10px] font-mono uppercase text-gray-400">
            Avg Confidence
          </span>
          <div className="font-mono text-2xl font-bold text-gray-100">
            {metrics.averageConfidence}%
          </div>
          <span className="text-[10px] font-mono text-cyan-400 block">
            Model signal conviction
          </span>
        </div>
      </div>
    </div>
  );
}
